name: Ansible

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: list
        run: ls -la

      - name: ping
        run: ansible all -i inventory.yaml -m ping
